//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersItems
    {
        public int ID { get; set; }
        public Nullable<int> OrdersID { get; set; }
        public Nullable<int> Products { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products1 { get; set; }
    }
}
