//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrdersItems = new HashSet<OrdersItems>();
        }
    
        public int ID { get; set; }
        public string ArticulOrders { get; set; }
        public Nullable<System.DateTime> OrdersDate { get; set; }
        public Nullable<System.DateTime> OrdersDelivery { get; set; }
        public Nullable<int> PvzID { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> VerificationCode { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Pvz Pvz { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<OrdersItems> OrdersItems { get; set; }
    }
}
