//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrdersItems = new HashSet<OrdersItems>();
        }
    
        public int ID { get; set; }
        public string ArticulProducts { get; set; }
        public string NameProducts { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ManufacturID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Skidka { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufactur Manufactur { get; set; }
        public virtual ICollection<OrdersItems> OrdersItems { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
