//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pvz
    {
        public Pvz()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IndexPvz { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> House { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
